version: "3.8"

services:
  n8n:
    image: n8nio/n8n:1.109.1
    container_name: n8n
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:5678"   # host:container
    volumes:
      - n8n_data:/home/node/.n8n
    # Basic healthcheck (n8n exposes /healthz)
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5678/healthz"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  n8n_data:
    driver: local
